services:
  api:
    build: .
    container_name: wss13_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - wss13_network
    volumes:
      - ./src:/app/src
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: wss13_db
    restart: always
    environment:
      POSTGRES_USER: wss13_user
      POSTGRES_PASSWORD: euemas12
      POSTGRES_DB: wss13
    volumes:
      - wss13_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wss13_network

  redis:
    image: redis:7-alpine
    container_name: wss13_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - wss13_redis:/data
    networks:
      - wss13_network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: wss13_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - wss13_network

networks:
  wss13_network:
    driver: bridge

volumes:
  wss13_pgdata:
  wss13_redis:
